# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wouldyourather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wouldyourather
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'
  pod 'Parse'

  target 'wouldyouratherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wouldyouratherUITests' do
    # Pods for testing
  end

end
